/* eslint-disable react/no-unescaped-entities */
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import Head from "next/head";
import { useEffect } from "react";
import Contact from "../components/Index/Contact";
import Intro from "../components/Index/Intro";
import ShortAbout from "../components/Index/ShortAbout";
import ShortAchivement from "../components/Index/ShortAchivement";
import ShortSkills from "../components/Index/ShortSkills";
import SortPortfolio from "../components/Index/SortPortfolio";
gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  useEffect(() => {
    gsap.to("progress", {
      value: 100,
      ease: "none",
      scrollTrigger: { scrub: 0.3 },
    });
  }, []);

  const skillStyle = {
    background:
      "url(https://i.ibb.co/TYL1TrZ/wordpress-3288417.png)",
    backgroundSize: "cover",
    backgroundPosition: "center center",
    backgroundAttachment: "fixed",
  };
  const achievementStyle = {
    background:
      "url(https://i.ibb.co/RSZD5rB/support-6773819.png)",
    backgroundSize: "cover",
    backgroundPosition: "center center",
    backgroundAttachment: "fixed",
  };

  return (
    <div>
      <div className="">
        <Head>
          <title>Shounak Raj</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <progress max="100" value="0" className="z-20"></progress>
        <section className="mb-36 p-8">
          <Intro />
        </section>
        <section className="mb-36 p-8">
          <ShortAbout />
        </section>
        <section className="mb-36" style={skillStyle}>
          <div className="bg-[#000000b3] w-full p-8">
            <ShortSkills />
          </div>
        </section>
        <section className="relative mb-36 p-8">
          {/* <AnimateBG/> */}
          <SortPortfolio />
        </section>
        <section className="mb-36" style={achievementStyle}>
          <div className="bg-[#000000b3] w-full p-8">
            <ShortAchivement />
          </div>
        </section>
        <section className="mb-16 p-8">
          <Contact />
        </section>
      </div>
    </div>
  );
}
