/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import { useContext } from "react";
import Project from "../helperComponent/Project";
import blood from "../Imgs/portfolio/blood.png";
import management from "../Imgs/portfolio/management.png";
import netflix from "../Imgs/portfolio/netflix.png";
import numberGuess from "../Imgs/portfolio/numberGuess.png";
import openai from "../Imgs/portfolio/openai.png";
import powerOdd from "../Imgs/portfolio/powerOdd.png";
import weather from "../Imgs/portfolio/weather.png";
import shareRide from "../Imgs/portfolio/shareRide.png";
import fintrackerio from "../Imgs/portfolio/fintrackerio.png";
import certi from "../Imgs/portfolio/certi.png";
import { AppContext } from "../pages/_app";

const Portfolio = () => {
  const [myTheme] = useContext<any>(AppContext);
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:min-h-screen flex justify-center">
        <div className="p-8">
          <h2
            className={`font-oleo underline underline-offset-4 decoration-wavy decoration-2 text-7xl text-center text-primary ${
              myTheme == "light" || myTheme == "emerald" || myTheme == "luxury"
                ? "drop-shadow-titleBlack"
                : "drop-shadow-titleWhite"
            }`}
          >
            Portfolio
          </h2>
          <h4 className="text-lg text-center text-[#aeaeae]">
            Check my porjects with code and you can call me if you are
            interested to hire me
          </h4>
          {/* portfolio start */}
          <div className="portfolio mt-12 text-lg md:flex md:flex-wrap gap-4">
            {/* FintrackerIO app */}
            <Project
              img={fintrackerio}
              title="Finance Tracker"
              overview="Finance tracking app for recording all income and expense of each date, month & year."
              technology="Next.JS, Tailwind Css, Express.js, MySql."
              // repository="https://github.com/shounaksarker"
              demo="https://fintrackerio-stage.vercel.app/"
            />
            {/* Certificate Validation */}
            <Project
              img={certi}
              title="Certificate Validation"
              overview="People of the ward applied and get councilor's certificates through this app."
              technology="Next.js, Tailwind, Laravel, MySql"
              // repository="https://github.com/shounaksarker"
              demo="https://eseba.chittaranjandas.com/"
            />
            {/* Share Ride */}
            <Project
              img={shareRide}
              height={150}
              width={250}
              title="Share Ride"
              overview="People who use Pathao bike/car ride, can share their live location and details with others."
              technology="React.js, Tailwind, React-leaflet (Map), Rest API"
              // repository="https://github.com/shounaksarker"
              demo="https://pages.pathao.com/share-ride/YY75g6H7cT7AKXnnTY3Cwg=="
            />
            {/* Netflix */}
            <Project
              img={netflix}
              title="Netflix"
              overview="A website where user can watch the trailer of new trendy movie or series."
              technology="React, Firebase, Flex-box, React-youtube."
              repository="https://github.com/shounaksarker/Netflix-clone"
              demo="https://netflix-snk.web.app/"
            />
            {/* Image by AI */}
            <Project
              img={openai}
              title="Image by AI"
              overview="This website is made for generating image by human prompt (text to image) & variating image"
              technology="React.js, Tailwind Css, Express.js, OpenAI"
              repository="https://github.com/shounaksarker/ai-image-generator"
              demo="https://aipicgen.onrender.com/"
            />
            {/* Number Guess Game */}
            <Project
              img={numberGuess}
              title="Number Guess Game"
              overview="In this game user gets clue and have to predict the number."
              technology="React, React-router, Bootstrap."
              repository="https://number-guess-snk.netlify.app/"
              demo="https://github.com/shounaksarker/Number-guess-game"
            />
            {/* Weather App */}
            <Project
              img={weather}
              title="Weather App"
              overview="This app shows weather details of the day and next 3 days of a ci-img."
              technology="React, Bootstrap."
              repository="https://github.com/shounaksarker/weatherApp"
              demo="https://web-app-snk.netlify.app/"
            />
            {/* PowerOdd */}
            <Project
              img={powerOdd}
              title="OTP - Authentication"
              overview="Signup Through Phone OTP"
              technology="React, Firebase, Bootstrap, React Router."
              repository="https://github.com/shounaksarker/phone-authentication"
              demo="https://phone-auth-snk.web.app "
            />
            {/*Management App */}
            <Project
              img={management}
              title="Management App"
              overview="A management app for tracing all income and expense of a religious organization."
              technology="Next.JS, Firebase,TypeScipt, Tailwind Css, Prisma."
              repository="https://github.com/shounaksarker/ManagementApp"
              demo="https://temp-manage.vercel.app"
            />
            {/* Blood App */}
            <Project
              img={blood}
              title="Blood Bank"
              overview="To create a profile for donating blood"
              technology="React, Firebase, Firebase hosting, React-hook-form"
              repository="https://github.com/shounaksarker/Blood-bank"
              demo="https://blood-app-snk.web.app/"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Portfolio;
