/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import { SiTailwindcss, SiVercel } from "react-icons/si";
import bootstrap from '../Imgs/Skills/bootstrap.png';
import css from '../Imgs/Skills/css.png';
import html5 from '../Imgs/Skills/html.png';
import js from '../Imgs/Skills/js.png';
import mui from '../Imgs/Skills/mui.png';
import rRouter from '../Imgs/Skills/react-router.png';
import reactjs from '../Imgs/Skills/react.png';
import sass from '../Imgs/Skills/sass.png';
import cpp from '../Imgs/Skills/c++.png';
import express from '../Imgs/Skills/express.png';
import firebase from '../Imgs/Skills/fireabse.png';
import git from '../Imgs/Skills/git.png';
import github from '../Imgs/Skills/github.png';
import heroku from '../Imgs/Skills/heroku.png';
import mongo from '../Imgs/Skills/mongodb.png';
import node from '../Imgs/Skills/nodejs.png';
import ps from '../Imgs/Skills/ps.png';
import xd from '../Imgs/Skills/xd.png';
import next from '../Imgs/Skills/next.png';
import vercel from '../Imgs/Skills/vercel.png';
import wordpress from '../Imgs/Skills/wordpress.png';
import { AppContext } from "./_app";
const Skills = () => {
  const [myTheme, ] = useContext<any>(AppContext);
  return (
    <div className="lg:min-h-screen flex justify-center">
      <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-8">
      <h2 className={`font-oleo underline decoration-wavy decoration-2 text-7xl text-center text-primary ${(myTheme == "light") || (myTheme == "emerald") || (myTheme == "luxury") ? "drop-shadow-titleBlack" : "drop-shadow-titleWhite"}`} >
        Skills
      </h2>
        <h4 className="text-lg text-center">
          Find out my skill set, what do I know and where I am perfect for.
        </h4>
        {/* box  */}
        <div className="md:flex justify-center items-center space-y-10 md:space-y-0 md:space-x-10 xl:space-x-20 mt-24">
            {/* 1st box - front end */}
            <div className={`flex-col space-y-3 p-5 bg-[#eeeeee] rounded-xl shadow-skill md:h-[550px] md:w-[32%] text-black ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"}`}>
                <h4 className="text-xl underline text-center">** Frontend **</h4>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={html5} alt="images" className='mr-4' width={40}/>
                    HTML5
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={css} alt="images" className='mr-4' width={40}/>
                    CSS3
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={bootstrap} alt="images" className='mr-4' width={40}/>
                    Bootstrap
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <SiTailwindcss className='text-blue-400 text-3xl mr-6'/>
                    Tailwind
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={mui} alt="images" className='mr-5' width={30}/>
                    Material UI
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={sass} alt="images" className='mr-4' width={40}/>
                    Sass
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={js} alt="images" className='mr-6' width={30}/>
                    JavaScript
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={reactjs} alt="images" className='mr-4' width={40}/>
                    React
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={next} alt="images" className='mr-4' width={30}/>
                    Next Js
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={rRouter} alt="images" className='mr-4' width={40}/>
                    React Router
                </div>
            </div>

            {/* 2nd box - backend + hosting  */}
            <div className='flex flex-col justify-between space-y-10 md:space-y-0 md:h-[550px] md:w-[32%]'>
              {/* backend */}
              <div className={`flex-col space-y-3 p-5 bg-[#eeeeee] rounded-xl shadow-skill text-black ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"}`}>
              <h4 className="text-xl underline text-center">** Backend **</h4>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={node} alt="images" className='mr-4' width={40}/>
                    Node Js
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={express} alt="images" className='mr-4' width={40}/>
                    Express Js
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={mongo} alt="images" className='mr-4' width={40}/>
                    MongoDB
                </div>
              </div>
              {/* hosting  */}
              <div className={`flex-col space-y-3 p-5 bg-[#eeeeee] rounded-xl shadow-skill ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"} text-black`}>
              <h4 className="text-xl underline text-center">** Hosting **</h4>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={firebase} alt="images" className='mr-4' width={40}/>
                    Firebase
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={heroku} alt="images" className='mr-4' width={40}/>
                    Heroku
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={github} alt="images" className='mr-4' width={40}/>
                    Github pages
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={vercel} alt="images" className='mr-4' width={40}/>
                    Vercel
                </div>
              </div>
            </div>

            {/* 3rd div */}
            <div className='flex flex-col justify-between space-y-10 md:space-y-0 md:h-[550px] md:w-[32%]'>
              {/* language */}
              <div className={`flex-col space-y-3 p-5 bg-[#eeeeee] rounded-xl shadow-skill ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"} text-black`}>
              <h4 className="text-xl underline text-center">** Language **</h4>
                <div className='flex justify-start items-center text-xl'>
                <Image src={js} alt="images" className='mr-6' width={30}/>
                    JavaScipt
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={cpp} alt="images" className='mr-4' width={40}/>
                    C++
                </div>
              </div>
              {/* Version Control  */}
              <div className={`flex-col space-y-3 p-4 bg-[#eeeeee] rounded-xl shadow-skill ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"} text-black`}>
              <h4 className="text-xl underline text-center">** Version Control **</h4>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={git} alt="images" className='mr-4' width={40}/>
                    Git
                </div>
              </div>
              {/* tools  */}
              <div className={`flex-col space-y-3 p-5 bg-[#eeeeee] rounded-xl shadow-skill ${myTheme == "light" ? "shadow-[#aaaaaa]" : "shadow-primary"} text-black`}>
              <h4 className="text-xl underline text-center">** Tools **</h4>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={wordpress} alt="images" className='mr-4' width={40}/>
                    WordPress
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={xd} alt="images" className='mr-4' width={40}/>
                    Adobe XD
                </div>
                <div className='flex justify-start items-center text-xl'>
                    <Image src={ps} alt="images" className='mr-4' width={40}/>
                    Adobe Photoshop
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default Skills;
